[[redirects]]
  from = "/phinisi"
  to = "/"
  status = 200

[[redirects]]
  from = "/about"
  to = "/"
  status = 200

[[redirects]]
  from = "/travel"
  to = "/"
  status = 200

[[redirects]]
  from = "/tips"
  to = "/"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/"
  status = 200