[[redirects]]
  from = "/phinisi"
  to = "/"
  status = 200

[[redirects]]
  from = "/about"
  to = "/"
  status = 200

[[redirects]]
  from = "/travel"
  to = "/"
  status = 200

[[redirects]]
  from = "/collaboration"
  to = "/"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/"
  status = 200

[[redirects]]
  from = "/panrita"
  to = "/"
  status = 200

[[redirects]]
  from = "/tamparang"
  to = "/"
  status = 200

[[redirects]]
  from = "/lopi"
  to = "/"
  status = 200

[[redirects]]
  from = "/bali"
  to = "/"
  status = 200

[[redirects]]
  from = "/sulawesi"
  to = "/"
  status = 200

[[redirects]]
  from = "/rajaampat"
  to = "/"
  status = 200

[[redirects]]
  from = "/sumba"
  to = "/"
  status = 200

[[redirects]]
  from = "/flores"
  to = "/"
  status = 200

[[redirects]]
  from = "/komodo"
  to = "/"
  status = 200